### ISSUE TITLE
Review bpo-15871: Online docs: make index search always available.

### ISSUE THREAD

**Issue by iritkatriel** [python/docs-community#39]
[An old open issue](https://bugs.python.org/issue15871) that you may be able to resolve.

**Comment by CAM-Gerlach** [comment]
The current "Quick Search" seems to be fairly effective in using and prioritizing index hits, such that (if I'm not just using google) it almost always seems to find what I'm looking for (and thus I was not able to duplicate the poor results suggested by the earlier comments in the BPO issue). A realtime search using only the index popping up results as users type in the search box would be useful, but it seems non-trivial to implement especially if the plan is to move to a more modern docs theme.

@pradyunsg Is there any plan for Furo to offer something like this?

**Comment by pradyunsg** [comment]
> @pradyunsg Is there any plan for Furo to offer something like this?

No.

I empathise and agree that would be a significantly better UX -- I don't think a Sphinx theme is the correct place to completely rework how Sphinx's search works though. :)

---

I'm not sure what the issue is about, and how that would be related to a Sphinx theme that Python's documentation does not even use. The b.p.o issue seems to be start by describing Windows Help, but also mentions things like bad search results on the online site (I can't reproduce the report in https://bugs.python.org/issue15871#msg170048 -- https://docs.python.org/3/search.html?q=random, but others do provide suboptimal results -- https://docs.python.org/3/search.html?q=if). 

Anyway, based on what I'm reading in that b.p.o issue, I think what's actionable here is more along the lines of "improve search results" rather than "rework what the search UX is".

**Comment by CAM-Gerlach** [comment]
> how that would be related to a Sphinx theme that Python's documentation does not even use.

Sorry, I was just curious if you had experience with or input on this, and I thought there was at least a tentative proposal to move CPython's docs to a more modern theme, which might have been able to address this.

**Comment by encukou** [comment]
Oh, this *is* about docs.python.org, which is lacking compared to the CHM version of the docs. Sorry for changing the title.

The issue seems to have been solved in Sphinx 1.2 (2013): https://github.com/sphinx-doc/sphinx/issues/1067

**Comment by encukou** [comment]
Hm, I can replicate the bad resulds mentioned in the 2014 comments -- for `print` and `with`.

**Comment by encukou** [comment]
Also, coming from #42: searching for symbols like `/` should yield the correct docs.

**Comment by CAM-Gerlach** [comment]
See #44 for some additional directly related discussion

**Comment by pradyunsg** [comment]
x-ref: https://github.com/python/cpython/issues/60075

**Comment by AA-Turner** [comment]
This is now https://github.com/python/cpython/issues/60075, discussion should happen on that issue as noted in the May 2022 meeting.

A
