### ISSUE TITLE
Review bpo-5901: missing meta-info in documentation pdf

### ISSUE THREAD

**Issue by iritkatriel** [python/docs-community#40]
[An old open issue](https://bugs.python.org/issue5901) that you may be able to resolve.

**Comment by CAM-Gerlach** [comment]
The issue seems to be resolved, at least in my testing. The PDF docs (at least those I spot-checked) all seem to have the `Title` set to the correct documentation title, and the `Author` to `Guido van Rossum, [sic] and the Python development team` (albeit with a spurious comma). I'm not sure if there's really a useful value for `Subject` or `Keywords` or a way to set it.

**Comment by encukou** [comment]
That seems to be coming from here: https://github.com/python/cpython/blob/main/Doc/conf.py#L142
Do you want to fix the comma? With my English skills I don't feel comfortable arguing about comma placement.

**Comment by CAM-Gerlach** [comment]
Thanks, opened as python/cpython#32386 . It seems I don't have at least triage rights over there, so I'll need someone to apply the `skip news` and `skip issue` labels to the issue, given its a fairly trivial change.

**Comment by hugovk** [comment]
Labelled!

**Comment by CAM-Gerlach** [comment]
Looks like that was merged, and with everything else already fixed I think this can be closed
