### ISSUE TITLE
Review bpo-21956: Doc files deleted from repo are not deleted from docs.python.org.

### ISSUE THREAD

**Issue by iritkatriel** [python/docs-community#41]
[An old open issue](https://bugs.python.org/issue21956) that you may be able to resolve.

**Comment by CAM-Gerlach** [comment]
Thanks. The issue seems to be resolved and presumably can be closed, as it seems in the intervening 8 years the adoption of the modern Sphinx rendering system and the hosting backend have resulted in documentation being appropriately deleted when it no longer exists in the source, as the link doc no longer exists and gives a 404, even for Python 3.4.

**Comment by encukou** [comment]
Hm, was there a change to the hosting backend? I know nothing about these things.
Do we know for sure files are being deleted, or should we double-check (and if so, where?)

**Comment by hugovk** [comment]
It happened in February with 3.11 due to a PDF build failure and some caching problems:

* https://github.com/python/docsbuild-scripts/issues/124

And earlier in 2017, fixed by changing a `cp` to `rsync` (but keeping `cp` for archives):

* https://github.com/python/docsbuild-scripts/issues/10

Ping also @JulienPalard.

**Comment by JulienPalard** [comment]
Yes as mentionned by @hugovk it's fixed since 2017 but it could still happen in very unfortunate conditions.

To be very precise:

- Today we don't use "html-only builds", so if the script crash nothing gets updated at all on docs.python.org (old files are kept, new files are not added).
- This year, when it happened (see [#124](https://github.com/python/docsbuild-scripts/issues/124)), we were triggering hourly "html-only builds" for `/dev/` because devs like fast updates and we still don't have https://github.com/python/psf-salt/issues/226.

If https://github.com/python/psf-salt/issues/226 gets done, or if any experience using html-only builds are done, AND a crash happen during the PDF build, it would result in the following situation:
- HTML get updated by html-only builds
- old files are not deleted

(Old files are not deleted by html-only builds because it would delete PDFs...)

Hopefully build errors are monitored using Sentry, I don't know who receive the notifications though, I know I receive them and I bet Ee receives them.

**Comment by encukou** [comment]
Ah, OK. I think it's fine if an emergency workaround build system keeps deleted files, as long as regular builds are fine. Thanks for confirming!
