### ISSUE TITLE
Mobile friendly theme for wiki.python.org

### ISSUE THREAD

**Issue by Mariatta** [python/docs-community#7]
Wiki.python.org is not mobile friendly.

It would be great to have a mobile theme for wiki.python.org. Though I personally don't have CSS / styling / art skills, so all I can do is provide moral support and perhaps merge the PR 😅

I wasn't able to locate the source code for the wiki, and I wasn't sure who "owns" or "hosts" the wiki, so I asked in The PSF's Discourse: https://discuss.python.org/t/wiki-python-org-is-not-mobil-friendly/8700

Some info:

- Hosting of the wiki is configured in psf-salt: https://github.com/python/psf-salt/blob/8c29e89e500bd1ad48c112e0144d574e89d13e01/pillar/base/moin.sls#L2-L7
- The wiki is powered by [moinmoin](https://moinmo.in/)
- General documentation on how to develop moinmoin theme: https://moinmo.in/MoinDev/ThemeDevelopment
- wiki.python.org is using europython moinmoin theme: http://moinmo.in/ThemeMarket/Europython.
- Source code of the europython theme is currently on Mercurial: http://hg.sheep.art.pl/moin-europython/ (what's the license)

Some thoughts and questions:
- We can fork the europython theme and improve it?
- Or perhaps we should develop a theme for us and make it look closer to python-docs-theme, or python.org?
- Or perhaps we should just use a pre-existing more modern moinmoin theme? Looks like the official theme itself is quite mobile friendly?

**Comment by ewdurbin** [comment]
The configuration noted is an attempt to migrate moin to salt that never came to fruition, BUT... it is running under management of salt as of August.

As far as the current theme goes, we are indeed running off of the linked mercurial repository... with a couple of (inconsequential, primarily) local changes applied. Due to the history of maintenance for the service, this is currently part of the "data" for the wiki that is backed up, but could be brought into configuration management. But regardless, changes applied to the upstream could easily be applied to wiki.python.org.

I don't have any opinion on the best course of action, but am happy to help get whatever is chosen rolled out.

**Comment by pradyunsg** [comment]
The most-modern theme I could find is https://moinmo.in/ThemeMarket/memodump, which is on GitHub as well: https://github.com/dossist/moinmoin-memodump

Last updated in Oct 2014, at the time of writing.

**Comment by hugovk** [comment]
See https://github.com/malemburg/moin-europython-theme/pull/1 for a PR to the EuroPython theme to make it minimally mobile-friendly.

**Comment by willingc** [comment]
@Mariatta I'm going to go ahead and close this now that I see the wiki is able to be shrunk to a mobile width. If we want to explore further, let's discuss and take up with the PSF :sunny:
